blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://quizfreely.com/discord
    about: "You can ask questions and also post bug reports or feature requests on Quizfreely's discord server"
